# Change Service Port
server:
  port: 9002

# Spring Config
spring:
  application:
    name: USER-SERVICE

  # Get Configuration from Git
  config:
    import: configserver:http://localhost:9296

  # zipkin and sleuth config
  zipkin:
    base-url: http://127.0.0.1:9411/

# Synchronous communication via Resilience4j
resilience4j:
  circuitbreaker:
    instances:
      departmentService:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        eventConsumerBufferSize: 10

# Actuator management
management:
  endpoints:
    web:
      exposure:
        include: health, circuits
  endpoint:
    health:
      show-details: always