server:
  port: 8080

spring:
  # Application Name
  application:
    name: spring-security-client

  # MySQL Database Configuration
  datasource:
    url: jdbc:mysql://localhost:3306/user-registration?createDatabaseIfNotExist=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA Configurations
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  # Spring Security OAuth 2.0
  security:
    oauth2:
      client:
        registration:
          api-client-oidc:
            provider: spring
            client-id: api-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8080/login/oauth2/code/{registrationId}"
            scope: openid
            client-name: api-client-oidc
          api-client-authorization-code:
            provider: spring
            client-id: api-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8080/authorized"
            scope: api.read
            client-name: api-client-authorization-code
        provider:
          spring:
            issuer-uri: http://auth-server:9000

# Remove Banner from Console
  main:
    banner-mode: off