server:
  port: 8082

spring:
  # Application Name
  application:
    name: spring-security-client

  # MySQL Database Configuration
  datasource:
    url: jdbc:mysql://localhost:3306/user-registration?createDatabaseIfNotExist=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA Configurations
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update