# Change Service Port
server:
  port: 9191

# Spring Config name and Cloud routing
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: USER_SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
        - id: DEPARTMENT_SERVICE
          uri: lb://DEPARTMENT-SERVICE
          predicates:
            - Path=/departments/**

# Eureka Client initialize
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
