# Change Service Port
server:
  port: 9001

# Spring Config
spring:
  application:
    name: DEPARTMENT-SERVICE

  # Get Configuration from Git
  config:
    import: configserver:http://localhost:9296


