# Change Service Port
server:
  port: 9001

# Spring Config
spring:
  application:
    name: DEPARTMENT-SERVICE

  # Get Configuration from Git
  config:
    import: configserver:http://localhost:9296

  # zipkin and sleuth config
  zipkin:
    base-url: http://127.0.0.1:9411/

