package com.rootlabs.spring.data.jpa.tutorial.entity;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
//Default table is "student" auto generated by entity class name
//Define new table name called "tbl_student" using @Table annotation
@Table(
        // Table name
        name = "tbl_student",

        // Define constraints
            //email id is to be unique
            uniqueConstraints = @UniqueConstraint(
                    name = "emailid_unique",
                    columnNames = "email_address"
            )
)
public class Student {

    // Specifies that the StudentId field is the primary key and uses a sequence for its value generation.
    @Id
    @SequenceGenerator(
            name = "student_sequence",
            sequenceName = "student_sequence",
            allocationSize = 1
    )
    @GeneratedValue(
            strategy = GenerationType.SEQUENCE,
            generator = "student_sequence"
    )
    private Long StudentId;
    private String firstName;
    private String lastName;

    //Default column is "emailId" auto generated by entity property name
    //Define new column name called "email_address" using @Column annotation
    @Column(
            name = "email_address",

            // email_address should not be null
            nullable = false
    )
    private String emailId;

    // Use Embeddable class called Guardian
    @Embedded
    private Guardian guardian;

}
